CREATE TABLE tbl_board (
  bno INT AUTO_INCREMENT PRIMARY KEY, 
  title VARCHAR(500) NOT NULL,
  content VARCHAR(2000) NOT NULL,
  writer VARCHAR(50) NOT NULL,
  regdate DATETIME DEFAULT NOW(), -- CURRENT_TIMESTAMP
  updatedate DATETIME DEFAULT NOW(), -- CURRENT_TIMESTAMP
  delflag BOOLEAN DEFAULT FALSE
);